--CREATE DATABASE InvoiceDb

CREATE TABLE MasterLanguage
(
	LanguageId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	LanguageName VARCHAR(50) NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME
);

CREATE TABLE MasterCurrency
(
	CurrencyId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CurrencyName VARCHAR(50) NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME
);

CREATE TABLE MasterCompany
(
	CompanyId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CompanyName VARCHAR(50) NOT NULL,
	CompanyAddress VARCHAR(150) NOT NULL,
	CompanyLogo VARCHAR(MAX) NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME
);

CREATE TABLE MasterMetric
(
	MetricId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	MetricName VARCHAR(50) NOT NULL,
	MetricCode VARCHAR(3) NOT NULL,
	MetricDescription VARCHAR(150) NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME
);

CREATE TABLE MasterInvoiceStatus
(
	InvoiceStatusId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	InvoiceStatus VARCHAR(50) NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME
);

CREATE TABLE Discount
(
	DiscountId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DiscountCode VARCHAR(50) NOT NULL,
	DiscountValue DECIMAL NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME
);

CREATE TABLE InvoiceHeader
(
	InvoiceId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	InvocieNo VARCHAR(7) NOT NULL,
	InvoiceStatus INT NOT NULL DEFAULT 0,
	LanguageId INT NOT NULL,
	CurrencyId INT NOT NULL,
	InvoiceFrom VARCHAR(150) NOT NULL,
	CompanyId INT NOT NULL,
	InvoiceDate DATETIME NOT NULL,
	InvoiceDue DATETIME NOT NULL,
	InvoicePON VARCHAR(6) NOT NULL,
	InvoiceSubTotal DECIMAL NOT NULL,
	DiscountCode VARCHAR(20) NOT NULL,
	DiscountPercentage DECIMAL NOT NULL,
	DiscountValue DECIMAL NOT NULL,
	InvoiceTotal DECIMAL NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME
	FOREIGN KEY (LanguageId) REFERENCES MasterLanguage (LanguageId),
	FOREIGN KEY (CurrencyId) REFERENCES MasterCurrency (CurrencyId),
	FOREIGN KEY (CompanyId) REFERENCES MasterCompany (CompanyId),
	FOREIGN KEY (InvoiceStatus) REFERENCES MasterInvoiceStatus (InvoiceStatusId)
);

CREATE TABLE InvoiceDetail
(
	InvoiceDetailId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	InvoiceId INT NOT NULL,
	ItemName VARCHAR(MAX) NOT NULL,
	ItemQty DECIMAL NOT NULL,
	ItemRate DECIMAL NOT NULL,
	MetricId INT NOT NULL,
	ItemAmount DECIMAL NOT NULL,
	CreateBy VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedBy VARCHAR(50),
	UpdatedAt DATETIME,
	FOREIGN KEY (MetricId) REFERENCES MasterMetric (MetricId),
	FOREIGN KEY (InvoiceId) REFERENCES InvoiceHeader (InvoiceId)
);